/* Copyright 2025-2026 Pierre-Nicolas SORMANI, aka Ark'Anoryn (@arkanoryn)
**
** This program is free software: you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation, either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include QMK_KEYBOARD_H
#include "farkann_v2.h"
#include "combos/combos.h"
#include "combos/generated/combos.h"

#define __EXTRA_ROW__ KC_A, KC_B, KC_C
#define __TMP_EMPTY KC_0, KC_0, KC_0, KC_0, KC_0, KC_0, KC_0, KC_0, KC_0, KC_0

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_GRAPHITE] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __NUMBERS_ROW_____,
#endif // FARKANN_NUMBER_ROW
        ___GRAPHITE_ROW_1___, ___GRAPHITE_ROW_2___, ___GRAPHITE_ROW_3___, __EXTRA_ROW__, __THUMBS__________),
    [_QWERTY] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __NUMBERS_ROW_____,
#endif // FARKANN_NUMBER_ROW
        ___QWERTY_ROW_1___, ___QWERTY_ROW_2___, ___QWERTY_ROW_3___, __EXTRA_ROW__, __THUMBS__________),
    [_GAME] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __NUMBERS_ROW_____,
#endif // FARKANN_NUMBER_ROW
        ___GAME_ROW_1___, ___GAME_ROW_2___, ___GAME_ROW_3___, __EXTRA_ROW__, __THUMBS__________),
    [_COLEMAK] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __NUMBERS_ROW_____,
#endif // FARKANN_NUMBER_ROW
        ___COLEMAK_ROW_1___, ___COLEMAK_ROW_2___, ___COLEMAK_ROW_3___, __EXTRA_ROW__, __THUMBS__________),
    [_STURDY] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __NUMBERS_ROW_____,
#endif // FARKANN_NUMBER_ROW
        ___STURDY_ROW_1___, ___STURDY_ROW_2___, ___STURDY_ROW_3___, __EXTRA_ROW__, __THUMBS__________),
    [_ACTIONS] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __NUMBERS_ROW_____,
#endif // FARKANN_NUMBER_ROW
        ___ACTIONS_ROW_1___, ___ACTIONS_ROW_2___, ___ACTIONS_ROW_3___, __EXTRA_ROW__, __THUMBS__________),
    [_SYMBOLS] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        ___SYMBOLS_ROW_1___,
#endif // FARKANN_NUMBER_ROW
        ___SYMBOLS_ROW_1___, ___SYMBOLS_ROW_2___, ___SYMBOLS_ROW_3___, __EXTRA_ROW__, ___SYMBOLS_THUMBS__________),
    [_ACCENTS] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        __TMP_EMPTY,
#endif // FARKANN_NUMBER_ROW
        __TMP_EMPTY, __TMP_EMPTY, __TMP_EMPTY, __EXTRA_ROW__, __THUMBS__________),
    [_NUMPAD_SOUND] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        ___NUMPAD_SOUND_ROW_1___,
#endif // FARKANN_NUMBER_ROW
        ___NUMPAD_SOUND_ROW_1___, ___NUMPAD_SOUND_ROW_2___, ___NUMPAD_SOUND_ROW_3___, __EXTRA_ROW__, ___NUMPAD_SOUND_THUMBS__________),
    [_CONFIG] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        ___CONFIG_ROW_1___,
#endif // FARKANN_NUMBER_ROW
        ___CONFIG_ROW_1___, ___CONFIG_ROW_2___, ___CONFIG_ROW_3___, __EXTRA_ROW__, ___CONFIG_THUMBS__________),
    [_FN] = LAYOUT(
#ifdef FARKANN_NUMBER_ROW
        ___FN_ROW_1___,
#endif // FARKANN_NUMBER_ROW
        ___FN_ROW_1___, ___FN_ROW_2___, ___FN_ROW_3___, __EXTRA_ROW__, ___FN_THUMBS__________),
};

// Combo definitions
const combo_t PROGMEM combos[] = {
  COMBO(GRAPHITE_DEL_WORD_COMBO, GRAPHITE_DEL_WORD),
  COMBO(GRAPHITE_CONFIG_LAYER_COMBO, GRAPHITE_CONFIG_LAYER),
  COMBO(GRAPHITE_TAB_C_COMBO, GRAPHITE_TAB_C),
  COMBO(GRAPHITE_EXLM_COMBO, GRAPHITE_EXLM),
  COMBO(GRAPHITE_QUES_COMBO, GRAPHITE_QUES),
  COMBO(GRAPHITE_SFT_ENT_COMBO, GRAPHITE_SFT_ENT),
  COMBO(GRAPHITE_C_ENT_COMBO, GRAPHITE_C_ENT),
  COMBO(GRAPHITE_ARE_COMBO, GRAPHITE_ARE),
  COMBO(GRAPHITE_EAT_COMBO, GRAPHITE_EAT),
  COMBO(GRAPHITE_LEARN_COMBO, GRAPHITE_LEARN),
  COMBO(GRAPHITE_DEVELOPER_COMBO, GRAPHITE_DEVELOPER),
  COMBO(GRAPHITE_A___COMBO, GRAPHITE_A__),
  COMBO(GRAPHITE_ABOUT_COMBO, GRAPHITE_ABOUT),
  COMBO(GRAPHITE_AFTER_COMBO, GRAPHITE_AFTER),
  COMBO(GRAPHITE_AGAIN_COMBO, GRAPHITE_AGAIN),
  COMBO(GRAPHITE_AGAINST_COMBO, GRAPHITE_AGAINST),
  COMBO(GRAPHITE_ALL_COMBO, GRAPHITE_ALL),
  COMBO(GRAPHITE_ALSO_COMBO, GRAPHITE_ALSO),
  COMBO(GRAPHITE_AND_COMBO, GRAPHITE_AND),
  COMBO(GRAPHITE_ANOTHER_COMBO, GRAPHITE_ANOTHER),
  COMBO(GRAPHITE_ANY_COMBO, GRAPHITE_ANY),
  COMBO(GRAPHITE_AROUND_COMBO, GRAPHITE_AROUND),
  COMBO(GRAPHITE_AS_COMBO, GRAPHITE_AS),
  COMBO(GRAPHITE_ASK_COMBO, GRAPHITE_ASK),
  COMBO(GRAPHITE_AT_COMBO, GRAPHITE_AT),
  COMBO(GRAPHITE_BACK_COMBO, GRAPHITE_BACK),
  COMBO(GRAPHITE_BE_COMBO, GRAPHITE_BE),
  COMBO(GRAPHITE_BECAUSE_COMBO, GRAPHITE_BECAUSE),
  COMBO(GRAPHITE_BECOME_COMBO, GRAPHITE_BECOME),
  COMBO(GRAPHITE_BEFORE_COMBO, GRAPHITE_BEFORE),
  COMBO(GRAPHITE_BEGIN_COMBO, GRAPHITE_BEGIN),
  COMBO(GRAPHITE_BETWEEN_COMBO, GRAPHITE_BETWEEN),
  COMBO(GRAPHITE_BIRTHDAY_COMBO, GRAPHITE_BIRTHDAY),
  COMBO(GRAPHITE_BOTH_COMBO, GRAPHITE_BOTH),
  COMBO(GRAPHITE_BUT_COMBO, GRAPHITE_BUT),
  COMBO(GRAPHITE_BY_COMBO, GRAPHITE_BY),
  COMBO(GRAPHITE_CALL_COMBO, GRAPHITE_CALL),
  COMBO(GRAPHITE_CAN_COMBO, GRAPHITE_CAN),
  COMBO(GRAPHITE_CANNOT_COMBO, GRAPHITE_CANNOT),
  COMBO(GRAPHITE_CHANGE_COMBO, GRAPHITE_CHANGE),
  COMBO(GRAPHITE_CHILD_COMBO, GRAPHITE_CHILD),
  COMBO(GRAPHITE_COME_COMBO, GRAPHITE_COME),
  COMBO(GRAPHITE_CONSIDER_COMBO, GRAPHITE_CONSIDER),
  COMBO(GRAPHITE_COULD_COMBO, GRAPHITE_COULD),
  COMBO(GRAPHITE_COURSE_COMBO, GRAPHITE_COURSE),
  COMBO(GRAPHITE_DAY_COMBO, GRAPHITE_DAY),
  COMBO(GRAPHITE_DEVELOP_COMBO, GRAPHITE_DEVELOP),
  COMBO(GRAPHITE_DO_COMBO, GRAPHITE_DO),
  COMBO(GRAPHITE_DOWN_COMBO, GRAPHITE_DOWN),
  COMBO(GRAPHITE_DURING_COMBO, GRAPHITE_DURING),
  COMBO(GRAPHITE_EACH_COMBO, GRAPHITE_EACH),
  COMBO(GRAPHITE_EARLY_COMBO, GRAPHITE_EARLY),
  COMBO(GRAPHITE_END_COMBO, GRAPHITE_END),
  COMBO(GRAPHITE_EVEN_COMBO, GRAPHITE_EVEN),
  COMBO(GRAPHITE_EYE_COMBO, GRAPHITE_EYE),
  COMBO(GRAPHITE_FACE_COMBO, GRAPHITE_FACE),
  COMBO(GRAPHITE_FACT_COMBO, GRAPHITE_FACT),
  COMBO(GRAPHITE_FEEL_COMBO, GRAPHITE_FEEL),
  COMBO(GRAPHITE_FEW_COMBO, GRAPHITE_FEW),
  COMBO(GRAPHITE_FIND_COMBO, GRAPHITE_FIND),
  COMBO(GRAPHITE_FIRST_COMBO, GRAPHITE_FIRST),
  COMBO(GRAPHITE_FOLLOW_COMBO, GRAPHITE_FOLLOW),
  COMBO(GRAPHITE_FOR_COMBO, GRAPHITE_FOR),
  COMBO(GRAPHITE_FORM_COMBO, GRAPHITE_FORM),
  COMBO(GRAPHITE_FROM_COMBO, GRAPHITE_FROM),
  COMBO(GRAPHITE_GENERAL_COMBO, GRAPHITE_GENERAL),
  COMBO(GRAPHITE_GET_COMBO, GRAPHITE_GET),
  COMBO(GRAPHITE_GIVE_COMBO, GRAPHITE_GIVE),
  COMBO(GRAPHITE_GO_COMBO, GRAPHITE_GO),
  COMBO(GRAPHITE_GOOD_COMBO, GRAPHITE_GOOD),
  COMBO(GRAPHITE_GOVERN_COMBO, GRAPHITE_GOVERN),
  COMBO(GRAPHITE_GREAT_COMBO, GRAPHITE_GREAT),
  COMBO(GRAPHITE_GROUP_COMBO, GRAPHITE_GROUP),
  COMBO(GRAPHITE_HAND_COMBO, GRAPHITE_HAND),
  COMBO(GRAPHITE_HAVE_COMBO, GRAPHITE_HAVE),
  COMBO(GRAPHITE_HE_COMBO, GRAPHITE_HE),
  COMBO(GRAPHITE_HEAD_COMBO, GRAPHITE_HEAD),
  COMBO(GRAPHITE_HELP_COMBO, GRAPHITE_HELP),
  COMBO(GRAPHITE_HERE_COMBO, GRAPHITE_HERE),
  COMBO(GRAPHITE_HIGH_COMBO, GRAPHITE_HIGH),
  COMBO(GRAPHITE_HOLD_COMBO, GRAPHITE_HOLD),
  COMBO(GRAPHITE_HOME_COMBO, GRAPHITE_HOME),
  COMBO(GRAPHITE_HOUSE_COMBO, GRAPHITE_HOUSE),
  COMBO(GRAPHITE_HOW_COMBO, GRAPHITE_HOW),
  COMBO(GRAPHITE_HOWEVER_COMBO, GRAPHITE_HOWEVER),
  COMBO(GRAPHITE_I__COMBO, GRAPHITE_I_),
  COMBO(GRAPHITE_IF_COMBO, GRAPHITE_IF),
  COMBO(GRAPHITE_IN_COMBO, GRAPHITE_IN),
  COMBO(GRAPHITE_INCREASE_COMBO, GRAPHITE_INCREASE),
  COMBO(GRAPHITE_INTEREST_COMBO, GRAPHITE_INTEREST),
  COMBO(GRAPHITE_INTO_COMBO, GRAPHITE_INTO),
  COMBO(GRAPHITE_IT_COMBO, GRAPHITE_IT),
  COMBO(GRAPHITE_JUST_COMBO, GRAPHITE_JUST),
  COMBO(GRAPHITE_KEEP_COMBO, GRAPHITE_KEEP),
  COMBO(GRAPHITE_KNOW_COMBO, GRAPHITE_KNOW),
  COMBO(GRAPHITE_KNOWLEDGE_COMBO, GRAPHITE_KNOWLEDGE),
  COMBO(GRAPHITE_LARGE_COMBO, GRAPHITE_LARGE),
  COMBO(GRAPHITE_LAST_COMBO, GRAPHITE_LAST),
  COMBO(GRAPHITE_LATE_COMBO, GRAPHITE_LATE),
  COMBO(GRAPHITE_LEAD_COMBO, GRAPHITE_LEAD),
  COMBO(GRAPHITE_LEAVE_COMBO, GRAPHITE_LEAVE),
  COMBO(GRAPHITE_LIFE_COMBO, GRAPHITE_LIFE),
  COMBO(GRAPHITE_LIKE_COMBO, GRAPHITE_LIKE),
  COMBO(GRAPHITE_LINE_COMBO, GRAPHITE_LINE),
  COMBO(GRAPHITE_LITTLE_COMBO, GRAPHITE_LITTLE),
  COMBO(GRAPHITE_LONG_COMBO, GRAPHITE_LONG),
  COMBO(GRAPHITE_LOOK_COMBO, GRAPHITE_LOOK),
  COMBO(GRAPHITE_MAKE_COMBO, GRAPHITE_MAKE),
  COMBO(GRAPHITE_MAN_COMBO, GRAPHITE_MAN),
  COMBO(GRAPHITE_MANY_COMBO, GRAPHITE_MANY),
  COMBO(GRAPHITE_MAY_COMBO, GRAPHITE_MAY),
  COMBO(GRAPHITE_MEAN_COMBO, GRAPHITE_MEAN),
  COMBO(GRAPHITE_MIGHT_COMBO, GRAPHITE_MIGHT),
  COMBO(GRAPHITE_MORE_COMBO, GRAPHITE_MORE),
  COMBO(GRAPHITE_MOST_COMBO, GRAPHITE_MOST),
  COMBO(GRAPHITE_MOVE_COMBO, GRAPHITE_MOVE),
  COMBO(GRAPHITE_MUST_COMBO, GRAPHITE_MUST),
  COMBO(GRAPHITE_NATION_COMBO, GRAPHITE_NATION),
  COMBO(GRAPHITE_NEED_COMBO, GRAPHITE_NEED),
  COMBO(GRAPHITE_NEVER_COMBO, GRAPHITE_NEVER),
  COMBO(GRAPHITE_NEW_COMBO, GRAPHITE_NEW),
  COMBO(GRAPHITE_NO_COMBO, GRAPHITE_NO),
  COMBO(GRAPHITE_NOT_COMBO, GRAPHITE_NOT),
  COMBO(GRAPHITE_NOW_COMBO, GRAPHITE_NOW),
  COMBO(GRAPHITE_NUMBER_COMBO, GRAPHITE_NUMBER),
  COMBO(GRAPHITE_OF_COMBO, GRAPHITE_OF),
  COMBO(GRAPHITE_OFF_COMBO, GRAPHITE_OFF),
  COMBO(GRAPHITE_OLD_COMBO, GRAPHITE_OLD),
  COMBO(GRAPHITE_ON_COMBO, GRAPHITE_ON),
  COMBO(GRAPHITE_ONE_COMBO, GRAPHITE_ONE),
  COMBO(GRAPHITE_ONLY_COMBO, GRAPHITE_ONLY),
  COMBO(GRAPHITE_OPEN_COMBO, GRAPHITE_OPEN),
  COMBO(GRAPHITE_OR_COMBO, GRAPHITE_OR),
  COMBO(GRAPHITE_ORDER_COMBO, GRAPHITE_ORDER),
  COMBO(GRAPHITE_OTHER_COMBO, GRAPHITE_OTHER),
  COMBO(GRAPHITE_OUT_COMBO, GRAPHITE_OUT),
  COMBO(GRAPHITE_OVER_COMBO, GRAPHITE_OVER),
  COMBO(GRAPHITE_OWN_COMBO, GRAPHITE_OWN),
  COMBO(GRAPHITE_PART_COMBO, GRAPHITE_PART),
  COMBO(GRAPHITE_PEOPLE_COMBO, GRAPHITE_PEOPLE),
  COMBO(GRAPHITE_PERSON_COMBO, GRAPHITE_PERSON),
  COMBO(GRAPHITE_PLACE_COMBO, GRAPHITE_PLACE),
  COMBO(GRAPHITE_PLAN_COMBO, GRAPHITE_PLAN),
  COMBO(GRAPHITE_PLAY_COMBO, GRAPHITE_PLAY),
  COMBO(GRAPHITE_POINT_COMBO, GRAPHITE_POINT),
  COMBO(GRAPHITE_POSSIBLE_COMBO, GRAPHITE_POSSIBLE),
  COMBO(GRAPHITE_PRESENT_COMBO, GRAPHITE_PRESENT),
  COMBO(GRAPHITE_PROBLEM_COMBO, GRAPHITE_PROBLEM),
  COMBO(GRAPHITE_PROGRAM_COMBO, GRAPHITE_PROGRAM),
  COMBO(GRAPHITE_PUBLIC_COMBO, GRAPHITE_PUBLIC),
  COMBO(GRAPHITE_REAL_COMBO, GRAPHITE_REAL),
  COMBO(GRAPHITE_RIGHT_COMBO, GRAPHITE_RIGHT),
  COMBO(GRAPHITE_RUN_COMBO, GRAPHITE_RUN),
  COMBO(GRAPHITE_SAME_COMBO, GRAPHITE_SAME),
  COMBO(GRAPHITE_SAY_COMBO, GRAPHITE_SAY),
  COMBO(GRAPHITE_SCHOOL_COMBO, GRAPHITE_SCHOOL),
  COMBO(GRAPHITE_SEE_COMBO, GRAPHITE_SEE),
  COMBO(GRAPHITE_SEEM_COMBO, GRAPHITE_SEEM),
  COMBO(GRAPHITE_SET_COMBO, GRAPHITE_SET),
  COMBO(GRAPHITE_SHE_COMBO, GRAPHITE_SHE),
  COMBO(GRAPHITE_SHOULD_COMBO, GRAPHITE_SHOULD),
  COMBO(GRAPHITE_SHOW_COMBO, GRAPHITE_SHOW),
  COMBO(GRAPHITE_SINCE_COMBO, GRAPHITE_SINCE),
  COMBO(GRAPHITE_SMALL_COMBO, GRAPHITE_SMALL),
  COMBO(GRAPHITE_SO_COMBO, GRAPHITE_SO),
  COMBO(GRAPHITE_SOME_COMBO, GRAPHITE_SOME),
  COMBO(GRAPHITE_STAND_COMBO, GRAPHITE_STAND),
  COMBO(GRAPHITE_STATE_COMBO, GRAPHITE_STATE),
  COMBO(GRAPHITE_STILL_COMBO, GRAPHITE_STILL),
  COMBO(GRAPHITE_SUCH_COMBO, GRAPHITE_SUCH),
  COMBO(GRAPHITE_SYSTEM_COMBO, GRAPHITE_SYSTEM),
  COMBO(GRAPHITE_TAKE_COMBO, GRAPHITE_TAKE),
  COMBO(GRAPHITE_TELL_COMBO, GRAPHITE_TELL),
  COMBO(GRAPHITE_THAN_COMBO, GRAPHITE_THAN),
  COMBO(GRAPHITE_THAT_COMBO, GRAPHITE_THAT),
  COMBO(GRAPHITE_THE_COMBO, GRAPHITE_THE),
  COMBO(GRAPHITE_THEIR_COMBO, GRAPHITE_THEIR),
  COMBO(GRAPHITE_THEM_COMBO, GRAPHITE_THEM),
  COMBO(GRAPHITE_THEN_COMBO, GRAPHITE_THEN),
  COMBO(GRAPHITE_THERE_COMBO, GRAPHITE_THERE),
  COMBO(GRAPHITE_THESE_COMBO, GRAPHITE_THESE),
  COMBO(GRAPHITE_THEY_COMBO, GRAPHITE_THEY),
  COMBO(GRAPHITE_THING_COMBO, GRAPHITE_THING),
  COMBO(GRAPHITE_THINK_COMBO, GRAPHITE_THINK),
  COMBO(GRAPHITE_THIS_COMBO, GRAPHITE_THIS),
  COMBO(GRAPHITE_THOSE_COMBO, GRAPHITE_THOSE),
  COMBO(GRAPHITE_TIME_COMBO, GRAPHITE_TIME),
  COMBO(GRAPHITE_TO_COMBO, GRAPHITE_TO),
  COMBO(GRAPHITE_TOO_COMBO, GRAPHITE_TOO),
  COMBO(GRAPHITE_TURN_COMBO, GRAPHITE_TURN),
  COMBO(GRAPHITE_UNDER_COMBO, GRAPHITE_UNDER),
  COMBO(GRAPHITE_UP_COMBO, GRAPHITE_UP),
  COMBO(GRAPHITE_USE_COMBO, GRAPHITE_USE),
  COMBO(GRAPHITE_VERY_COMBO, GRAPHITE_VERY),
  COMBO(GRAPHITE_WANT_COMBO, GRAPHITE_WANT),
  COMBO(GRAPHITE_WAY_COMBO, GRAPHITE_WAY),
  COMBO(GRAPHITE_WE_COMBO, GRAPHITE_WE),
  COMBO(GRAPHITE_WELL_COMBO, GRAPHITE_WELL),
  COMBO(GRAPHITE_WHAT_COMBO, GRAPHITE_WHAT),
  COMBO(GRAPHITE_WHEN_COMBO, GRAPHITE_WHEN),
  COMBO(GRAPHITE_WHERE_COMBO, GRAPHITE_WHERE),
  COMBO(GRAPHITE_WHICH_COMBO, GRAPHITE_WHICH),
  COMBO(GRAPHITE_WHILE_COMBO, GRAPHITE_WHILE),
  COMBO(GRAPHITE_WHO_COMBO, GRAPHITE_WHO),
  COMBO(GRAPHITE_WHY_COMBO, GRAPHITE_WHY),
  COMBO(GRAPHITE_WILL_COMBO, GRAPHITE_WILL),
  COMBO(GRAPHITE_WITH_COMBO, GRAPHITE_WITH),
  COMBO(GRAPHITE_WITHOUT_COMBO, GRAPHITE_WITHOUT),
  COMBO(GRAPHITE_WORD_COMBO, GRAPHITE_WORD),
  COMBO(GRAPHITE_WORK_COMBO, GRAPHITE_WORK),
  COMBO(GRAPHITE_WORLD_COMBO, GRAPHITE_WORLD),
  COMBO(GRAPHITE_WOULD_COMBO, GRAPHITE_WOULD),
  COMBO(GRAPHITE_WRITE_COMBO, GRAPHITE_WRITE),
  COMBO(GRAPHITE_YEAR_COMBO, GRAPHITE_YEAR),
  COMBO(GRAPHITE_YOU_COMBO, GRAPHITE_YOU),
  COMBO(GRAPHITE_ING_COMBO, GRAPHITE_ING),
  COMBO(GRAPHITE_NT_COMBO, GRAPHITE_NT),
  COMBO(GRAPHITE_QUOTE_VE_COMBO, GRAPHITE_QUOTE_VE),
  COMBO(GRAPHITE_QUOTE_RE_COMBO, GRAPHITE_QUOTE_RE),
  COMBO(GRAPHITE_QUOTE_S_COMBO, GRAPHITE_QUOTE_S),
  COMBO(GRAPHITE_QUOTE_D_COMBO, GRAPHITE_QUOTE_D),
  COMBO(GRAPHITE_QUOTE_LL_COMBO, GRAPHITE_QUOTE_LL),
  COMBO(GRAPHITE_HI_COMBO, GRAPHITE_HI),
  COMBO(GRAPHITE_YEAH_COMBO, GRAPHITE_YEAH),
  COMBO(GRAPHITE_THANK_YOU_COMBO, GRAPHITE_THANK_YOU),
  COMBO(GRAPHITE_WTF_COMBO, GRAPHITE_WTF),
  COMBO(GRAPHITE_I_VE_COMBO, GRAPHITE_I_VE),
  COMBO(GRAPHITE_I_M_COMBO, GRAPHITE_I_M),
  COMBO(GRAPHITE_I_LL_COMBO, GRAPHITE_I_LL),
  COMBO(GRAPHITE_GOD_COMBO, GRAPHITE_GOD),
  COMBO(GRAPHITE_PROJECT_COMBO, GRAPHITE_PROJECT),
  COMBO(GRAPHITE_PRODUCT_COMBO, GRAPHITE_PRODUCT_COMBO),
  COMBO(GRAPHITE_LOST_COMBO, GRAPHITE_LOST),
  COMBO(GRAPHITE_LOOSE_COMBO, GRAPHITE_LOOSE),
};

// Add matrix_scan_user function for combo event task
void matrix_scan_user(void) {
  combo_event_task();
}

// Add keyboard_post_init_user function for initialization
void keyboard_post_init_user(void) {
#ifdef CYCLE_COMBO_ENABLE
  init_cycling_combos_state();
#endif
#ifdef CHORD_TEACHER_ENABLE
  init_teacher_state();
#endif
}

// Combo should trigger callback
bool combo_should_trigger(uint16_t combo_index, combo_t *combo, uint16_t keycode, keyrecord_t *record) {
  // Always allow config layer combo (needed to toggle chords back on)
  // As we would no longer be able to access the Config Layer without it
  if (combo_index == GRAPHITE_CONFIG_LAYER) return true;

#ifdef CHORD_TEACHER_ENABLE
  if (get_teacher_chord_mode() == TEACHER_CHORD_MODE_OFF) return false;
#endif // CHORD_TEACHER_ENABLE

  return true;
}
