/*
** This file contains the different keycode definition dedicated to Graphite.
** Here we are only looking at the generic 5 rows of the 3 alpha column.
**  If a keyboard has more key, around the rows, the modifications should be done in the keymap.c
**
** /!\ This layer requires the implementation of the symbols
*/
#pragma once

#include QMK_KEYBOARD_H
#include "ark_v1.h" // root_config
#include "layers.h" // each keyboard should have this file with the available layers enum
#include "symbols/symbols.h"

#ifndef CKC
#  define CKC(x) (SAFE_RANGE + x) // generate custom keycode from enum
#endif                            // CKC

#define __________ACCENTS_LEFT_ROW_1________ CW_TOGG, KC_ASTR, KC_AMPR, KC_PERCENT, CKC(CMD_REDO)
#define __________ACCENTS_LEFT_ROW_2________ KC_TAB, KC_DQUO, KC_EXLM, KC_QUES, CKC(CMD_UNDO)
#define __________ACCENTS_LEFT_ROW_3________ __X__, __X__, __X__, __X__, __X__

#ifdef FARKANN_FRENCH_ACCENTS
#define _________ACCENTS_RIGHT_ROW_1________ __X__, CKC(E_CIRC), CKC(U_GRAVE), CKC(I_CIRC), CKC(I_TREMA)
#define _________ACCENTS_RIGHT_ROW_2________ __X__, CKC(E_AIGU), CKC(E_GRAVE), CKC(A_GRAVE), CKC(O_CIRC)
#define _________ACCENTS_RIGHT_ROW_3________ __X__, CKC(C_CEDILLE), CKC(U_CIRC), CKC(A_CIRC), __X__
#elif FARKANN_GERMAN_ACCENTS
#define _________ACCENTS_RIGHT_ROW_1________ __X__, CKC(E_CIRC), CKC(U_GRAVE), CKC(I_CIRC), CKC(I_TREMA)
#define _________ACCENTS_RIGHT_ROW_2________ __X__, CKC(E_AIGU), CKC(E_GRAVE), CKC(A_GRAVE), CKC(O_CIRC)
#define _________ACCENTS_RIGHT_ROW_3________ __X__, CKC(C_CEDILLE), CKC(U_CIRC), CKC(A_CIRC), __X__
#endif

#define __ACCENTS_CORE_ROW_1___  __________ACCENTS_LEFT_ROW_1________, /* || */ _________ACCENTS_RIGHT_ROW_1________
#define __ACCENTS_CORE_ROW_2___  __________ACCENTS_LEFT_ROW_2________, /* || */ _________ACCENTS_RIGHT_ROW_2________
#define __ACCENTS_CORE_ROW_3___  __________ACCENTS_LEFT_ROW_3________, /* || */ _________ACCENTS_RIGHT_ROW_3________
#define __ACCENTS_EXTRA_ROW__ __EXTRA_ROW__

#ifdef FARKANN_EXTRA_COLS
#   define ___ACCENTS_ROW_1___ ___ROW_1_WITH_EXTRA_COLS(__ACCENTS_CORE_ROW_1___)
#   define ___ACCENTS_ROW_2___ ___ROW_2_WITH_EXTRA_COLS(__ACCENTS_CORE_ROW_2___)
#   define ___ACCENTS_ROW_3___ ___ROW_3_WITH_EXTRA_COLS(__ACCENTS_CORE_ROW_3___)
#else
#   define ___ACCENTS_ROW_1___ __ACCENTS_CORE_ROW_1___
#   define ___ACCENTS_ROW_2___ __ACCENTS_CORE_ROW_2___
#   define ___ACCENTS_ROW_3___ __ACCENTS_CORE_ROW_3___
#endif

#define ACCENT_L1 __X__
#define ACCENT_L2 KC_LSFT
#define ACCENT_L3 __X__
#define ACCENT_L4 __X__
#define ACCENT_L5 __X__
#define ACCENT_L6 __X__
#define ACCENT_R1 __X__
#define ACCENT_R2 LAYER_LOCK
#define ACCENT_R3 __X__
#define ACCENT_R4 __X__
#define ACCENT_R5 __X__
#define ACCENT_R6 __X__

#if THUMBCLUSTER_LEFT == 2
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_R4, ACCENT_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_R4, ACCENT_R5, ACCENT_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 3
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_R4, ACCENT_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_R4, ACCENT_R5, ACCENT_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 4
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_L3, ACCENT_L4
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L3, ACCENT_L4
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_L3, ACCENT_L4, ACCENT_R3, ACCENT_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L3, ACCENT_L4, ACCENT_R4, ACCENT_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L3, ACCENT_L4, ACCENT_R4, ACCENT_R5, ACCENT_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 5
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_L4, ACCENT_L5
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L4, ACCENT_L5
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_L4, ACCENT_L5, ACCENT_R3, ACCENT_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L4, ACCENT_L5, ACCENT_R4, ACCENT_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L4, ACCENT_L5, ACCENT_R4, ACCENT_R5, ACCENT_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 6
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_L4, ACCENT_L5, ACCENT_L6
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L4, ACCENT_L5, ACCENT_L6
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_L4, ACCENT_L5, ACCENT_L6, ACCENT_R3, ACCENT_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L4, ACCENT_L5, ACCENT_L6, ACCENT_R4, ACCENT_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACCENTS_THUMBS__________ ACCENT_L1, ACCENT_L2, ACCENT_L3, ACCENT_R1, ACCENT_R2, ACCENT_R3, ACCENT_L4, ACCENT_L5, ACCENT_L6, ACCENT_R4, ACCENT_R5, ACCENT_R6
#   endif // THUMBCLUSTER_RIGHT
#endif // THUMBCLUSTER_LEFT
