/*
** This file contains the different keycode definition dedicated to Graphite.
** Here we are only looking at the generic 5 rows of the 3 alpha column.
**  If a keyboard has more key, around the rows, the modifications should be done in the keymap.c
**
** /!\ This layer requires the implementation of the shortcuts
*/
#pragma once

#include QMK_KEYBOARD_H
#include "layers.h" // each keyboard should have this file with the available layers enum
#include "shortcuts/shortcuts.h"
#include "tap_dance/tap_dance.h"

#define __X__ KC_NO

#define TAB_NEXT LCTL(KC_TAB)
#define TAB_PREV RCS(KC_TAB)

#ifndef CKC
#  define CKC(x) (SAFE_RANGE + x) // generate custom keycode from enum
#endif                            // CKC

#define __________ACTIONS_LEFT_ROW_1________ TD(TD_ESC), TD(TD_SEARCH), CKC(ALFRED), KC_DEL, CKC(APP_PREV)
#define __________ACTIONS_LEFT_ROW_2________ KC_TAB, CKC(CMD_SAVE), __X__, __X__, CKC(APP_NEXT)
// #define __________ACTIONS_LEFT_ROW_2________ KC_TAB, CKC(CMD_SAVE), TD(TD_SELECTION_BACKWARD), TD(TD_SELECTION_FORWARD), CKC(APP_NEXT)
#define __________ACTIONS_LEFT_ROW_3________ CKC(TASK_MNGR), CKC(CMD_REDO), CKC(CMD_UNDO), TD(TD_NEW_WINDOW), CKC(APP_CLOSE)

#define _________ACTIONS_RIGHT_ROW_1________ KC_PGUP, TD(TD_JUMP_BACKWARD), TD(TD_JUMP_FORWARD), KC_HOME, KC_END
#define _________ACTIONS_RIGHT_ROW_2________ KC_PGDN, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT
#define _________ACTIONS_RIGHT_ROW_3________ CKC(TAB_REOPEN), TD(TD_TAB_NEW), TD(TD_TAB_CLOSE), TAB_NEXT, TAB_PREV

#define __ACTIONS_CORE_ROW_1___  __________ACTIONS_LEFT_ROW_1________, /* || */ _________ACTIONS_RIGHT_ROW_1________
#define __ACTIONS_CORE_ROW_1___  __________ACTIONS_LEFT_ROW_1________, /* || */ _________ACTIONS_RIGHT_ROW_1________
#define __ACTIONS_CORE_ROW_2___  __________ACTIONS_LEFT_ROW_2________, /* || */ _________ACTIONS_RIGHT_ROW_2________
#define __ACTIONS_CORE_ROW_3___  __________ACTIONS_LEFT_ROW_3________, /* || */ _________ACTIONS_RIGHT_ROW_3________
#define __ACTIONS_EXTRA_ROW__ __EXTRA_ROW__

#ifdef FARKANN_EXTRA_COLS
#   define ___ACTIONS_ROW_1___ ___ROW_1_WITH_EXTRA_COLS(__ACTIONS_CORE_ROW_1___)
#   define ___ACTIONS_ROW_2___ ___ROW_2_WITH_EXTRA_COLS(__ACTIONS_CORE_ROW_2___)
#   define ___ACTIONS_ROW_3___ ___ROW_3_WITH_EXTRA_COLS(__ACTIONS_CORE_ROW_3___)
#else
#   define ___ACTIONS_ROW_1___ __ACTIONS_CORE_ROW_1___
#   define ___ACTIONS_ROW_2___ __ACTIONS_CORE_ROW_2___
#   define ___ACTIONS_ROW_3___ __ACTIONS_CORE_ROW_3___
#endif

#define ACTION_L1 TD(TD_COPY)
#define ACTION_L2 CKC(CMD_PASTE)
#define ACTION_L3 __X__
#define ACTION_L4 __X__
#define ACTION_L5 __X__
#define ACTION_L6 __X__
#define ACTION_R1 TD(TD_CUT)
#define ACTION_R2 LAYER_LOCK
#define ACTION_R3 __X__
#define ACTION_R4 __X__
#define ACTION_R5 __X__
#define ACTION_R6 __X__

#if THUMBCLUSTER_LEFT == 2
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_R4, ACTION_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_R4, ACTION_R5, ACTION_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 3
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_R4, ACTION_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_R4, ACTION_R5, ACTION_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 4
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_L3, ACTION_L4
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L3, ACTION_L4
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_L3, ACTION_L4, ACTION_R3, ACTION_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L3, ACTION_L4, ACTION_R4, ACTION_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L3, ACTION_L4, ACTION_R4, ACTION_R5, ACTION_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 5
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_L4, ACTION_L5
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L4, ACTION_L5
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_L4, ACTION_L5, ACTION_R3, ACTION_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L4, ACTION_L5, ACTION_R4, ACTION_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L4, ACTION_L5, ACTION_R4, ACTION_R5, ACTION_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 6
#   if THUMBCLUSTER_RIGHT == 2
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_L4, ACTION_L5, ACTION_L6
#   elif THUMBCLUSTER_RIGHT == 3
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L4, ACTION_L5, ACTION_L6
#   elif THUMBCLUSTER_RIGHT == 4
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_L4, ACTION_L5, ACTION_L6, ACTION_R3, ACTION_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L4, ACTION_L5, ACTION_L6, ACTION_R4, ACTION_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __ACTIONS_THUMBS__________ ACTION_L1, ACTION_L2, ACTION_L3, ACTION_R1, ACTION_R2, ACTION_R3, ACTION_L4, ACTION_L5, ACTION_L6, ACTION_R4, ACTION_R5, ACTION_R6
#   endif // THUMBCLUSTER_RIGHT
#endif // THUMBCLUSTER_LEFT
