/*
** This file contains the different keycode definition dedicated to Graphite.
** Here we are only looking at the generic 5 rows of the 3 alpha column.
**  If a keyboard has more key, around the rows, the modifications should be done in the keymap.c
**
*/
#pragma once

#include QMK_KEYBOARD_H
#include "ark_v1.h" // root_config
#include "layers.h" // each keyboard should have this file with the available layers enum

#define ___________NUMPAD_ROW_1_____________ KC_PAST, KC_P4, KC_P5, KC_P6, KC_PPLS
#define ___________NUMPAD_ROW_2_____________ KC_P0, KC_P1, KC_P2, KC_P3, KC_EQL
#define ___________NUMPAD_ROW_3_____________ KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PMNS

#define ____________SOUND_ROW_1_____________ KC_VOLU, KC_VOLD, KC_NUM, TG(_FN), __X__
#define ____________SOUND_ROW_2_____________ KC_MNXT, KC_LSFT, KC_LCTL, KC_LGUI, __X__
#define ____________SOUND_ROW_3_____________ KC_MPLY, __X__, __X__, __X__, __X__

#define __NUMPAD_SOUND_CORE_ROW_1___  ___________NUMPAD_ROW_1_____________, /* || */ ____________SOUND_ROW_1_____________
#define __NUMPAD_SOUND_CORE_ROW_2___  ___________NUMPAD_ROW_2_____________, /* || */ ____________SOUND_ROW_2_____________
#define __NUMPAD_SOUND_CORE_ROW_3___  ___________NUMPAD_ROW_3_____________, /* || */ ____________SOUND_ROW_3_____________
#define __NUMPAD_SOUND_EXTRA_ROW__ __EXTRA_ROW__

#ifdef FARKANN_EXTRA_COLS
#   define ___NUMPAD_SOUND_ROW_1___ ___ROW_1_WITH_EXTRA_COLS(__NUMPAD_SOUND_CORE_ROW_1___)
#   define ___NUMPAD_SOUND_ROW_2___ ___ROW_2_WITH_EXTRA_COLS(__NUMPAD_SOUND_CORE_ROW_2___)
#   define ___NUMPAD_SOUND_ROW_3___ ___ROW_3_WITH_EXTRA_COLS(__NUMPAD_SOUND_CORE_ROW_3___)
#else
#   define ___NUMPAD_SOUND_ROW_1___ __NUMPAD_SOUND_CORE_ROW_1___
#   define ___NUMPAD_SOUND_ROW_2___ __NUMPAD_SOUND_CORE_ROW_2___
#   define ___NUMPAD_SOUND_ROW_3___ __NUMPAD_SOUND_CORE_ROW_3___
#endif

#define NUMPAD_SOUND_L1 KC_ENT
#define NUMPAD_SOUND_L2 KC_DOT
#define NUMPAD_SOUND_L3 __X__
#define NUMPAD_SOUND_L4 __X__
#define NUMPAD_SOUND_L5 __X__
#define NUMPAD_SOUND_L6 __X__
#define NUMPAD_SOUND_R1 __X__
#define NUMPAD_SOUND_R2 LAYER_LOCK
#define NUMPAD_SOUND_R3 __X__
#define NUMPAD_SOUND_R4 __X__
#define NUMPAD_SOUND_R5 __X__
#define NUMPAD_SOUND_R6 __X__

#if THUMBCLUSTER_LEFT == 2
#   if THUMBCLUSTER_RIGHT == 2
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5, NUMPAD_SOUND_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 3
#   if THUMBCLUSTER_RIGHT == 2
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5, NUMPAD_SOUND_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 4
#   if THUMBCLUSTER_RIGHT == 2
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_L3, NUMPAD_SOUND_L4
#   elif THUMBCLUSTER_RIGHT == 3
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L3, NUMPAD_SOUND_L4
#   elif THUMBCLUSTER_RIGHT == 4
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_L3, NUMPAD_SOUND_L4, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L3, NUMPAD_SOUND_L4, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L3, NUMPAD_SOUND_L4, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5, NUMPAD_SOUND_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 5
#   if THUMBCLUSTER_RIGHT == 2
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5
#   elif THUMBCLUSTER_RIGHT == 3
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5
#   elif THUMBCLUSTER_RIGHT == 4
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5, NUMPAD_SOUND_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 6
#   if THUMBCLUSTER_RIGHT == 2
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_L6
#   elif THUMBCLUSTER_RIGHT == 3
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_L6
#   elif THUMBCLUSTER_RIGHT == 4
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_L6, NUMPAD_SOUND_R3, NUMPAD_SOUND_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_L6, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __NUMPAD_SOUND_THUMBS__________ NUMPAD_SOUND_L1, NUMPAD_SOUND_L2, NUMPAD_SOUND_L3, NUMPAD_SOUND_R1, NUMPAD_SOUND_R2, NUMPAD_SOUND_R3, NUMPAD_SOUND_L4, NUMPAD_SOUND_L5, NUMPAD_SOUND_L6, NUMPAD_SOUND_R4, NUMPAD_SOUND_R5, NUMPAD_SOUND_R6
#   endif // THUMBCLUSTER_RIGHT
#endif // THUMBCLUSTER_LEFT
