/*
** This file contains the different keycode definition dedicated to Graphite.
** Here we are only looking at the generic 5 rows of the 3 alpha column.
**  If a keyboard has more key, around the rows, the modifications should be done in the keymap.c
**
** /!\ This layer requires the implementation of the symbols
*/
#pragma once

#include QMK_KEYBOARD_H
#include "layers.h" // each keyboard should have this file with the available layers enum
#include "symbols/symbols.h"

#ifndef CKC
#  define CKC(x) (SAFE_RANGE + x) // generate custom keycode from enum
#endif                            // CKC

#define __SYMBOLS_CORE_ROW_1___ KC_CAPS,    KC_AT,  KC_HASH,KC_DOLLAR,  CKC(EURO),   /* || */ KC_SLSH,   KC_LBRC, KC_RBRC, KC_SCLN, __X__
#define __SYMBOLS_CORE_ROW_2___ KC_TILDE,   KC_GRV, KC_UNDS, KC_MINS,    KC_PLUS,     /* || */ KC_EQL,   KC_LPRN, KC_RPRN, KC_COLN, __X__
#define __SYMBOLS_CORE_ROW_3___ __X__,      KC_PIPE,KC_LT,  KC_GT,      KC_CIRC,     /* || */ __X__,     KC_LCBR, KC_RCBR, KC_BSLS, __X__
#define __SYMBOLS_EXTRA_ROW__ __EXTRA_ROW__

#ifdef FARKANN_EXTRA_COLS
#   define ___SYMBOLS_ROW_1___ ___ROW_1_WITH_EXTRA_COLS(__SYMBOLS_CORE_ROW_1___)
#   define ___SYMBOLS_ROW_2___ ___ROW_2_WITH_EXTRA_COLS(__SYMBOLS_CORE_ROW_2___)
#   define ___SYMBOLS_ROW_3___ ___ROW_3_WITH_EXTRA_COLS(__SYMBOLS_CORE_ROW_3___)
#else
#   define ___SYMBOLS_ROW_1___ __SYMBOLS_CORE_ROW_1___
#   define ___SYMBOLS_ROW_2___ __SYMBOLS_CORE_ROW_2___
#   define ___SYMBOLS_ROW_3___ __SYMBOLS_CORE_ROW_3___
#endif

#define SYMBOL_L1 __X__
#define SYMBOL_L2 __X__
#define SYMBOL_L3 __X__
#define SYMBOL_L4 __X__
#define SYMBOL_L5 __X__
#define SYMBOL_L6 __X__
#define SYMBOL_R1 KC_PERCENT
#define SYMBOL_R2 LAYER_LOCK
#define SYMBOL_R3 __X__
#define SYMBOL_R4 __X__
#define SYMBOL_R5 __X__
#define SYMBOL_R6 __X__

#if THUMBCLUSTER_LEFT == 2
#   if THUMBCLUSTER_RIGHT == 2
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_R4, SYMBOL_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_R4, SYMBOL_R5, SYMBOL_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 3
#   if THUMBCLUSTER_RIGHT == 2
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2
#   elif THUMBCLUSTER_RIGHT == 3
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3
#   elif THUMBCLUSTER_RIGHT == 4
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_R4, SYMBOL_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_R4, SYMBOL_R5, SYMBOL_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 4
#   if THUMBCLUSTER_RIGHT == 2
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_L3, SYMBOL_L4
#   elif THUMBCLUSTER_RIGHT == 3
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L3, SYMBOL_L4
#   elif THUMBCLUSTER_RIGHT == 4
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_L3, SYMBOL_L4, SYMBOL_R3, SYMBOL_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L3, SYMBOL_L4, SYMBOL_R4, SYMBOL_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L3, SYMBOL_L4, SYMBOL_R4, SYMBOL_R5, SYMBOL_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 5
#   if THUMBCLUSTER_RIGHT == 2
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_L4, SYMBOL_L5
#   elif THUMBCLUSTER_RIGHT == 3
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L4, SYMBOL_L5
#   elif THUMBCLUSTER_RIGHT == 4
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_L4, SYMBOL_L5, SYMBOL_R3, SYMBOL_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L4, SYMBOL_L5, SYMBOL_R4, SYMBOL_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L4, SYMBOL_L5, SYMBOL_R4, SYMBOL_R5, SYMBOL_R6
#   endif // THUMBCLUSTER_RIGHT
#elif THUMBCLUSTER_LEFT == 6
#   if THUMBCLUSTER_RIGHT == 2
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_L4, SYMBOL_L5, SYMBOL_L6
#   elif THUMBCLUSTER_RIGHT == 3
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L4, SYMBOL_L5, SYMBOL_L6
#   elif THUMBCLUSTER_RIGHT == 4
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_L4, SYMBOL_L5, SYMBOL_L6, SYMBOL_R3, SYMBOL_R4
#   elif THUMBCLUSTER_RIGHT == 5
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L4, SYMBOL_L5, SYMBOL_L6, SYMBOL_R4, SYMBOL_R5
#   elif THUMBCLUSTER_RIGHT == 6
#       define __SYMBOLS_THUMBS__________ SYMBOL_L1, SYMBOL_L2, SYMBOL_L3, SYMBOL_R1, SYMBOL_R2, SYMBOL_R3, SYMBOL_L4, SYMBOL_L5, SYMBOL_L6, SYMBOL_R4, SYMBOL_R5, SYMBOL_R6
#   endif // THUMBCLUSTER_RIGHT
#endif // THUMBCLUSTER_LEFT
