/* Copyright 2025 Pierre-Nicolas SORMANI, aka Ark'Anoryn (@arkanoryn)
**
** This program is free software: you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation, either version 2 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/*
** This file contains the different possibilities our keyboards can have for the Thumb Clusters.
*/

#pragma once

#include QMK_KEYBOARD_H

#define MEH_SPC     MEH_T(KC_SPC)
#define SFT_MAGIC   LSFT_T(MAGIC)

// #ifdef FARKANN_POWER_USER
#define THUMB_L1 SFT_MAGIC
#define THUMB_L2 MEH_SPC
#define THUMB_L3 LGUI_T(KC_ESC)
#define THUMB_L4 LCTL_T(S(KC_TAB))
#define THUMB_L5 LALT_T(KC_TAB)
#define THUMB_L6 KC_PGDN
#define THUMB_R1 RALT_T(ARCANE)
#define THUMB_R2 RSFT_T(KC_BSPC)
#define THUMB_R3 RGUI_T(KC_DEL)
#define THUMB_R4 RCTL_T(KC_ENT)
#define THUMB_R5 KC_HOME
#define THUMB_R6 KC_END
// #else
// #define THUMB_L1 KC_SPC
// #define THUMB_L2 KC_ESC
// #define THUMB_L3 KC_PGUP
// #define THUMB_L4 S(KC_TAB)
// #define THUMB_L5 KC_TAB
// #define THUMB_L6 QK_BOOT // KC_PGDN // THUMB_RAISE | THUMB_LOWER
// #define THUMB_R1 KC_BSPC
// #define THUMB_R2 KC_ENT
// #define THUMB_R3 QK_BOOT // KC_LSFT
// #define THUMB_R4 KC_RCTL
// #define THUMB_R5 KC_RALT
// #define THUMB_R6 KC_RGUI
// #endif // FARKANN_POWER_USER

#ifndef __THUMBS__________
#undef __THUMBS__________
#endif

// THUMBCLUSTER_LEFT == 2
#if THUMBCLUSTER_LEFT == 2 && THUMBCLUSTER_RIGHT == 2
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2
#elif THUMBCLUSTER_LEFT == 2 && THUMBCLUSTER_RIGHT == 3
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3
#elif THUMBCLUSTER_LEFT == 2 && THUMBCLUSTER_RIGHT == 4
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_R4
#elif THUMBCLUSTER_LEFT == 2 && THUMBCLUSTER_RIGHT == 5
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_R4, THUMB_R5
#elif THUMBCLUSTER_LEFT == 2 && THUMBCLUSTER_RIGHT == 6
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_R4, THUMB_R5, THUMB_R6

// THUMBCLUSTER_LEFT == 3
#elif THUMBCLUSTER_LEFT == 3 && THUMBCLUSTER_RIGHT == 2
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2
#elif THUMBCLUSTER_LEFT == 3 && THUMBCLUSTER_RIGHT == 3
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3
#elif THUMBCLUSTER_LEFT == 3 && THUMBCLUSTER_RIGHT == 4
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_R4
#elif THUMBCLUSTER_LEFT == 3 && THUMBCLUSTER_RIGHT == 5
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_R4, THUMB_R5
#elif THUMBCLUSTER_LEFT == 3 && THUMBCLUSTER_RIGHT == 6
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_R4, THUMB_R5, THUMB_R6

// THUMBCLUSTER_LEFT == 4
#elif THUMBCLUSTER_LEFT == 4 && THUMBCLUSTER_RIGHT == 2
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_L3, THUMB_L4
#elif THUMBCLUSTER_LEFT == 4 && THUMBCLUSTER_RIGHT == 3
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L3, THUMB_L4
#elif THUMBCLUSTER_LEFT == 4 && THUMBCLUSTER_RIGHT == 4
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_L3, THUMB_L4, THUMB_R3, THUMB_R4
#elif THUMBCLUSTER_LEFT == 4 && THUMBCLUSTER_RIGHT == 5
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L3, THUMB_L4, THUMB_R4, THUMB_R5
#elif THUMBCLUSTER_LEFT == 4 && THUMBCLUSTER_RIGHT == 6
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L3, THUMB_L4, THUMB_R4, THUMB_R5, THUMB_R6

// THUMBCLUSTER_LEFT == 5
#elif THUMBCLUSTER_LEFT == 5 && THUMBCLUSTER_RIGHT == 2
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_L4, THUMB_L5
#elif THUMBCLUSTER_LEFT == 5 && THUMBCLUSTER_RIGHT == 3
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L4, THUMB_L5
#elif THUMBCLUSTER_LEFT == 5 && THUMBCLUSTER_RIGHT == 4
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_L4, THUMB_L5, THUMB_R3, THUMB_R4
#elif THUMBCLUSTER_LEFT == 5 && THUMBCLUSTER_RIGHT == 5
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L4, THUMB_L5, THUMB_R4, THUMB_R5
#elif THUMBCLUSTER_LEFT == 5 && THUMBCLUSTER_RIGHT == 6
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L4, THUMB_L5, THUMB_R4, THUMB_R5, THUMB_R6

// THUMBCLUSTER_LEFT == 6
#elif THUMBCLUSTER_LEFT == 6 && THUMBCLUSTER_RIGHT == 2
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_L4, THUMB_L5, THUMB_L6
#elif THUMBCLUSTER_LEFT == 6 && THUMBCLUSTER_RIGHT == 3
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L4, THUMB_L5, THUMB_L6
#elif THUMBCLUSTER_LEFT == 6 && THUMBCLUSTER_RIGHT == 4
// #define __TEST_THUMBS__________  KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, QK_BOOT
#define __THUMBS__________  THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_L4, THUMB_L5, THUMB_L6, THUMB_R3, THUMB_R4
#elif THUMBCLUSTER_LEFT == 6 && THUMBCLUSTER_RIGHT == 5
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L4, THUMB_L5, THUMB_L6, THUMB_R4, THUMB_R5
#elif THUMBCLUSTER_LEFT == 6 && THUMBCLUSTER_RIGHT == 6
#define __THUMBS__________ THUMB_L1, THUMB_L2, THUMB_L3, THUMB_R1, THUMB_R2, THUMB_R3, THUMB_L4, THUMB_L5, THUMB_L6, THUMB_R4, THUMB_R5, THUMB_R6
#endif
