#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_DEBOUNCE 200

#define LEADER_TIMEOUT 250
#define LEADER_PER_KEY_TIMING
#define LEADER_KEY_STRICT_KEY_PROCESSING

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
